name: Setup Runner
description: Setup dependencies for the runner

runs: 
  using: "composite"
  steps: 
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: 16.4

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2.2'
        bundler-cache: true